/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-06-25 03:07:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.baldree.beans.TravelRecordBean;
import java.util.ArrayList;
import java.util.List;

public final class travelRecords_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.baldree.beans.TravelRecordBean");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    // Create a list to store JavaBean records.
    List<TravelRecordBean> travelRecords = new ArrayList<>();

    // Add travel records using the JavaBean constructor.
    travelRecords.add(new TravelRecordBean("Tennessee", "State", "Music, barbecue, and mountains", "Visiting Memphis", 1998));
    travelRecords.add(new TravelRecordBean("Florida", "State", "Beaches and theme parks", "Going to the beach", 2000));
    travelRecords.add(new TravelRecordBean("Georgia", "State", "Atlanta and southern history", "Exploring Atlanta", 2010));
    travelRecords.add(new TravelRecordBean("Texas", "State", "Large cities, food, and culture", "Trying local food", 2007));
    travelRecords.add(new TravelRecordBean("Mississippi", "State", "Southern culture and history", "Taking a road trip", 2005));

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Travel Records JavaBean Display</title>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("\n");
      out.write("        <h1>Travel Records Using a JavaBean</h1>\n");
      out.write("\n");
      out.write("        <p class=\"description\">\n");
      out.write("            This page displays travel information stored inside JavaBean objects.\n");
      out.write("            Each record includes the place name, location type, what the place is known for,\n");
      out.write("            my favorite activity, and the year visited.\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("        <h2>Field Descriptions</h2>\n");
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr>\n");
      out.write("                <th>Field Name</th>\n");
      out.write("                <th>Description</th>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>Place Name</td>\n");
      out.write("                <td>The name of the state or place visited.</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>Location Type</td>\n");
      out.write("                <td>Identifies whether the location is a state, country, or another type of place.</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>Best Known For</td>\n");
      out.write("                <td>Describes something the location is commonly known for.</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>Favorite Activity</td>\n");
      out.write("                <td>Shows what I enjoyed most while visiting that location.</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>Year Visited</td>\n");
      out.write("                <td>The year I visited the location.</td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("        <h2>Travel Record Data</h2>\n");
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr>\n");
      out.write("                <th>Record #</th>\n");
      out.write("                <th>Place Name</th>\n");
      out.write("                <th>Location Type</th>\n");
      out.write("                <th>Best Known For</th>\n");
      out.write("                <th>Favorite Activity</th>\n");
      out.write("                <th>Year Visited</th>\n");
      out.write("            </tr>\n");
      out.write("\n");
      out.write("            ");

                // Loop through the JavaBean records and display each one in the table.
                for (int i = 0; i < travelRecords.size(); i++) {
                    TravelRecordBean record = travelRecords.get(i);
            
      out.write("\n");
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td>");
      out.print( i + 1 );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( record.getPlaceName() );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( record.getLocationType() );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( record.getBestKnownFor() );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( record.getFavoriteActivity() );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( record.getYearVisited() );
      out.write("</td>\n");
      out.write("            </tr>\n");
      out.write("\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("        <p class=\"summary\">\n");
      out.write("            This assignment shows how a JavaBean can store data separately from the JSP page. The JSP page uses scriptlets to create JavaBean records and then displays the information in a formatted HTML table.\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
