/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-07-24 22:12:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

public final class alexMoviedelete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    /*
     * Converts special HTML characters into safe text before values
     * from the database are displayed on the web page.
     */
    public String escapeHtml(String value) {
        if (value == null) {
            return "";
        }

        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');

    /*
     * Database connection information used by the existing
     * Modules 5 & 6, 7, and 8 movie database project.
     */
    String databaseUrl =
            "jdbc:mysql://localhost:3306/CSD430?useSSL=false";

    String databaseUser = "student1";
    String databasePassword = "pass";

    /*
     * This is the same movie table used in the previous modules.
     */
    String tableName = "alexmoviesdata";

    /*
     * Each String array stored in this ArrayList represents one
     * movie record that will be displayed in the dropdown and table.
     */
    ArrayList<String[]> movieRecords =
            new ArrayList<String[]>();

    String successMessage = "";
    String errorMessage = "";

    /*
     * Reads the selected primary key from the HTML form.
     */
    String selectedMovieId =
            request.getParameter("movie_id");

    /*
     * The record is deleted only when the page receives a POST request.
     */
    boolean formSubmitted =
            "POST".equalsIgnoreCase(request.getMethod());

    Connection connection = null;
    PreparedStatement deleteStatement = null;
    Statement selectStatement = null;
    ResultSet resultSet = null;

    try {
        /*
         * Loads MySQL Connector/J 5.1.49.
         */
        Class.forName("com.mysql.jdbc.Driver");

        /*
         * Opens a connection to the existing CSD430 database.
         */
        connection = DriverManager.getConnection(
                databaseUrl,
                databaseUser,
                databasePassword
        );

        /*
         * Deletes the record selected in the dropdown.
         * A PreparedStatement is used so the key value is handled safely.
         */
        if (formSubmitted) {
            if (selectedMovieId != null
                    && !selectedMovieId.trim().isEmpty()) {

                try {
                    int movieId =
                            Integer.parseInt(
                                    selectedMovieId.trim()
                            );

                    String deleteSql =
                            "DELETE FROM "
                            + tableName
                            + " WHERE movie_id = ?";

                    deleteStatement =
                            connection.prepareStatement(deleteSql);

                    deleteStatement.setInt(1, movieId);

                    int numberDeleted =
                            deleteStatement.executeUpdate();

                    if (numberDeleted > 0) {
                        successMessage =
                                "Movie record "
                                + movieId
                                + " was deleted successfully.";
                    } else {
                        errorMessage =
                                "The selected movie record was not found.";
                    }

                } catch (NumberFormatException exception) {
                    errorMessage =
                            "The selected movie ID was not valid.";
                }

            } else {
                errorMessage =
                        "Please select a movie record to delete.";
            }
        }

        /*
         * Selects every record that remains after the delete operation.
         * These records are displayed in both the dropdown and table.
         */
        String selectSql =
                "SELECT movie_id, title, director, "
                + "release_year, genre, rating "
                + "FROM "
                + tableName
                + " ORDER BY movie_id";

        selectStatement =
                connection.createStatement();

        resultSet =
                selectStatement.executeQuery(selectSql);

        /*
         * Copies each database record into the ArrayList.
         */
        while (resultSet.next()) {
            String[] movie = new String[6];

            movie[0] =
                    String.valueOf(
                            resultSet.getInt("movie_id")
                    );

            movie[1] =
                    resultSet.getString("title");

            movie[2] =
                    resultSet.getString("director");

            movie[3] =
                    String.valueOf(
                            resultSet.getInt("release_year")
                    );

            movie[4] =
                    resultSet.getString("genre");

            movie[5] =
                    resultSet.getString("rating");

            movieRecords.add(movie);
        }

    } catch (ClassNotFoundException exception) {
        errorMessage =
                "The MySQL JDBC driver could not be loaded. "
                + "Make sure mysql-connector-java-5.1.49.jar "
                + "is inside WEB-INF/lib.";

    } catch (Exception exception) {
        errorMessage =
                "Database error: "
                + exception.getMessage();

    } finally {
        /*
         * Closes each database resource after it is used.
         */
        try {
            if (resultSet != null) {
                resultSet.close();
            }
        } catch (Exception exception) {
            // The resource could not be closed.
        }

        try {
            if (selectStatement != null) {
                selectStatement.close();
            }
        } catch (Exception exception) {
            // The resource could not be closed.
        }

        try {
            if (deleteStatement != null) {
                deleteStatement.close();
            }
        } catch (Exception exception) {
            // The resource could not be closed.
        }

        try {
            if (connection != null) {
                connection.close();
            }
        } catch (Exception exception) {
            // The resource could not be closed.
        }
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("    <meta name=\"viewport\"\n");
      out.write("          content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("    <title>Delete Movie Records</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\"\n");
      out.write("          href=\"alexstyle.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"page-container\">\n");
      out.write("\n");
      out.write("    <header>\n");
      out.write("        <h1>Delete Movie Records</h1>\n");
      out.write("\n");
      out.write("        <p class=\"description\">\n");
      out.write("            This page displays every record currently stored in the\n");
      out.write("            Alex Movies database table. Select a movie ID from the\n");
      out.write("            dropdown menu and submit the form to delete that record.\n");
      out.write("            After the deletion, the table and dropdown will immediately\n");
      out.write("            display all remaining movie records.\n");
      out.write("        </p>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    ");
 if (!successMessage.isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"success-message\">\n");
      out.write("            ");
      out.print( escapeHtml(successMessage) );
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if (!errorMessage.isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"error-message\">\n");
      out.write("            ");
      out.print( escapeHtml(errorMessage) );
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <section class=\"delete-section\">\n");
      out.write("\n");
      out.write("        <h2>Select a Movie Record to Delete</h2>\n");
      out.write("\n");
      out.write("        <p>\n");
      out.write("            The dropdown contains the primary key and title for each\n");
      out.write("            movie record currently stored in the database.\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("        <form action=\"alexMoviedelete.jsp\"\n");
      out.write("              method=\"post\"\n");
      out.write("              class=\"delete-form\">\n");
      out.write("\n");
      out.write("            <label for=\"movie_id\">\n");
      out.write("                Movie record:\n");
      out.write("            </label>\n");
      out.write("\n");
      out.write("            <select id=\"movie_id\"\n");
      out.write("                    name=\"movie_id\"\n");
      out.write("                    required\n");
      out.write("                    ");
      out.print( movieRecords.isEmpty()
                            ? "disabled"
                            : "" );
      out.write(">\n");
      out.write("\n");
      out.write("                ");
 if (movieRecords.isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("                    <option value=\"\">\n");
      out.write("                        No movie records are available\n");
      out.write("                    </option>\n");
      out.write("\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("\n");
      out.write("                    <option value=\"\"\n");
      out.write("                            selected\n");
      out.write("                            disabled>\n");
      out.write("                        Select a movie ID\n");
      out.write("                    </option>\n");
      out.write("\n");
      out.write("                    ");
 for (String[] movie : movieRecords) { 
      out.write("\n");
      out.write("\n");
      out.write("                        <option value=\"");
      out.print( escapeHtml(movie[0]) );
      out.write("\">\n");
      out.write("                            ID ");
      out.print( escapeHtml(movie[0]) );
      out.write("\n");
      out.write("                            -\n");
      out.write("                            ");
      out.print( escapeHtml(movie[1]) );
      out.write("\n");
      out.write("                        </option>\n");
      out.write("\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            </select>\n");
      out.write("\n");
      out.write("            <button type=\"submit\"\n");
      out.write("                    class=\"delete-button\"\n");
      out.write("                    ");
      out.print( movieRecords.isEmpty()
                            ? "disabled"
                            : "" );
      out.write(">\n");
      out.write("                Delete Selected Movie\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        ");
 if (!movieRecords.isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("            <p class=\"warning\">\n");
      out.write("                Warning: The selected movie will be permanently\n");
      out.write("                removed from the database.\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section class=\"records-section\">\n");
      out.write("\n");
      out.write("        <h2>Current Movie Records</h2>\n");
      out.write("\n");
      out.write("        <p>\n");
      out.write("            The table displays the movie ID, title, director,\n");
      out.write("            release year, genre, and rating for every record\n");
      out.write("            remaining in the database.\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("        <div class=\"table-container\">\n");
      out.write("\n");
      out.write("            <table>\n");
      out.write("\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Movie ID</th>\n");
      out.write("                        <th>Movie Title</th>\n");
      out.write("                        <th>Director</th>\n");
      out.write("                        <th>Release Year</th>\n");
      out.write("                        <th>Genre</th>\n");
      out.write("                        <th>Rating</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("\n");
      out.write("                <tbody>\n");
      out.write("\n");
      out.write("                    ");
 for (String[] movie : movieRecords) { 
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>\n");
      out.write("                                ");
      out.print( escapeHtml(movie[0]) );
      out.write("\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                ");
      out.print( escapeHtml(movie[1]) );
      out.write("\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                ");
      out.print( escapeHtml(movie[2]) );
      out.write("\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                ");
      out.print( escapeHtml(movie[3]) );
      out.write("\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                ");
      out.print( escapeHtml(movie[4]) );
      out.write("\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                ");
      out.print( escapeHtml(movie[5]) );
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
 if (movieRecords.isEmpty()) { 
      out.write("\n");
      out.write("\n");
      out.write("            <p class=\"empty-message\">\n");
      out.write("                All movie records have been deleted. The table heading\n");
      out.write("                remains visible, but there are no records to display.\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <nav class=\"navigation\">\n");
      out.write("        <a href=\"alexindex.jsp\">\n");
      out.write("            Return to Project Home\n");
      out.write("        </a>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
