/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-06-18 03:45:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Restaurant Feedback Form</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1>Restaurant Experience Feedback Form</h1>\n");
      out.write("\n");
      out.write("        <p>\n");
      out.write("            This form gathers feedback about a customer's restaurant visit.\n");
      out.write("            The information collected includes customer details, meal type,\n");
      out.write("            ratings, recommendations, and written comments.\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("        <form action=\"results.jsp\" method=\"post\">\n");
      out.write("\n");
      out.write("            <label for=\"customerName\">Customer Name:</label>\n");
      out.write("            <input type=\"text\" id=\"customerName\" name=\"customerName\" required>\n");
      out.write("\n");
      out.write("            <label for=\"email\">Email Address:</label>\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\" required>\n");
      out.write("\n");
      out.write("            <label for=\"visitDate\">Date of Visit:</label>\n");
      out.write("            <input type=\"date\" id=\"visitDate\" name=\"visitDate\" required>\n");
      out.write("\n");
      out.write("            <label for=\"mealType\">Meal Type:</label>\n");
      out.write("            <select id=\"mealType\" name=\"mealType\" required>\n");
      out.write("                <option value=\"\">Select a meal type</option>\n");
      out.write("                <option value=\"Breakfast\">Breakfast</option>\n");
      out.write("                <option value=\"Lunch\">Lunch</option>\n");
      out.write("                <option value=\"Dinner\">Dinner</option>\n");
      out.write("                <option value=\"Dessert\">Dessert</option>\n");
      out.write("            </select>\n");
      out.write("\n");
      out.write("            <p class=\"section-label\">Food Rating:</p>\n");
      out.write("            <div class=\"radio-group\">\n");
      out.write("                <input type=\"radio\" id=\"foodExcellent\" name=\"foodRating\" value=\"Excellent\" required>\n");
      out.write("                <label for=\"foodExcellent\">Excellent</label>\n");
      out.write("\n");
      out.write("                <input type=\"radio\" id=\"foodGood\" name=\"foodRating\" value=\"Good\">\n");
      out.write("                <label for=\"foodGood\">Good</label>\n");
      out.write("\n");
      out.write("                <input type=\"radio\" id=\"foodFair\" name=\"foodRating\" value=\"Fair\">\n");
      out.write("                <label for=\"foodFair\">Fair</label>\n");
      out.write("\n");
      out.write("                <input type=\"radio\" id=\"foodPoor\" name=\"foodRating\" value=\"Poor\">\n");
      out.write("                <label for=\"foodPoor\">Poor</label>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <p class=\"section-label\">Service Rating:</p>\n");
      out.write("            <div class=\"radio-group\">\n");
      out.write("                <input type=\"radio\" id=\"serviceExcellent\" name=\"serviceRating\" value=\"Excellent\" required>\n");
      out.write("                <label for=\"serviceExcellent\">Excellent</label>\n");
      out.write("\n");
      out.write("                <input type=\"radio\" id=\"serviceGood\" name=\"serviceRating\" value=\"Good\">\n");
      out.write("                <label for=\"serviceGood\">Good</label>\n");
      out.write("\n");
      out.write("                <input type=\"radio\" id=\"serviceFair\" name=\"serviceRating\" value=\"Fair\">\n");
      out.write("                <label for=\"serviceFair\">Fair</label>\n");
      out.write("\n");
      out.write("                <input type=\"radio\" id=\"servicePoor\" name=\"serviceRating\" value=\"Poor\">\n");
      out.write("                <label for=\"servicePoor\">Poor</label>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <p class=\"section-label\">What would you recommend?</p>\n");
      out.write("            <div class=\"checkbox-group\">\n");
      out.write("                <input type=\"checkbox\" id=\"appetizers\" name=\"recommendations\" value=\"Appetizers\">\n");
      out.write("                <label for=\"appetizers\">Appetizers</label>\n");
      out.write("\n");
      out.write("                <input type=\"checkbox\" id=\"mainCourse\" name=\"recommendations\" value=\"Main Course\">\n");
      out.write("                <label for=\"mainCourse\">Main Course</label>\n");
      out.write("\n");
      out.write("                <input type=\"checkbox\" id=\"desserts\" name=\"recommendations\" value=\"Desserts\">\n");
      out.write("                <label for=\"desserts\">Desserts</label>\n");
      out.write("\n");
      out.write("                <input type=\"checkbox\" id=\"drinks\" name=\"recommendations\" value=\"Drinks\">\n");
      out.write("                <label for=\"drinks\">Drinks</label>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <label for=\"comments\">Additional Comments:</label>\n");
      out.write("            <textarea id=\"comments\" name=\"comments\" rows=\"5\" required></textarea>\n");
      out.write("\n");
      out.write("            <div class=\"button-area\">\n");
      out.write("                <input type=\"submit\" value=\"Submit Feedback\">\n");
      out.write("                <input type=\"reset\" value=\"Clear Form\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
