/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-07-08 23:01:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.DriverManager");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');

    request.setCharacterEncoding("UTF-8");

    String databaseUrl = "jdbc:mysql://localhost:3306/CSD430?useSSL=false";
    String databaseUser = "student1";
    String databasePassword = "pass";

    String message = "";
    ArrayList<String[]> movieRecords = new ArrayList<String[]>();

    try {
        Class.forName("com.mysql.jdbc.Driver");

        Connection connection = DriverManager.getConnection(databaseUrl, databaseUser, databasePassword);

        // This section adds a new movie record when the form is submitted.
        if ("POST".equalsIgnoreCase(request.getMethod())) {
            String title = request.getParameter("title");
            String director = request.getParameter("director");
            String releaseYearText = request.getParameter("release_year");
            String genre = request.getParameter("genre");
            String rating = request.getParameter("rating");

            if (title != null && director != null && releaseYearText != null && genre != null && rating != null
                    && !title.trim().isEmpty()
                    && !director.trim().isEmpty()
                    && !releaseYearText.trim().isEmpty()
                    && !genre.trim().isEmpty()
                    && !rating.trim().isEmpty()) {

                int releaseYear = Integer.parseInt(releaseYearText);

                String insertSql = "INSERT INTO alexmoviesdata "
                        + "(title, director, release_year, genre, rating) "
                        + "VALUES (?, ?, ?, ?, ?)";

                PreparedStatement insertStatement = connection.prepareStatement(insertSql);
                insertStatement.setString(1, title);
                insertStatement.setString(2, director);
                insertStatement.setInt(3, releaseYear);
                insertStatement.setString(4, genre);
                insertStatement.setString(5, rating);
                insertStatement.executeUpdate();
                insertStatement.close();

                message = "New movie record added successfully.";
            } else {
                message = "Please complete every field before submitting the form.";
            }
        }

        // This section collects all movie records so they can be displayed in the HTML table.
        String selectSql = "SELECT movie_id, title, director, release_year, genre, rating "
                + "FROM alexmoviesdata ORDER BY movie_id";

        Statement selectStatement = connection.createStatement();
        ResultSet resultSet = selectStatement.executeQuery(selectSql);

        while (resultSet.next()) {
            String[] row = new String[6];

            row[0] = String.valueOf(resultSet.getInt("movie_id"));
            row[1] = resultSet.getString("title");
            row[2] = resultSet.getString("director");
            row[3] = String.valueOf(resultSet.getInt("release_year"));
            row[4] = resultSet.getString("genre");
            row[5] = resultSet.getString("rating");

            movieRecords.add(row);
        }

        resultSet.close();
        selectStatement.close();
        connection.close();

    } catch (Exception error) {
        message = "Database error: " + error.getMessage();
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Alex Baldree Movie Database</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <h1>Alex Baldree Movie Database</h1>\n");
      out.write("\n");
      out.write("    <p>\n");
      out.write("        This page is part of my Module 7 database project. It allows a user to add a new\n");
      out.write("        movie record to the existing CSD430 database and then displays all current records\n");
      out.write("        from the movie table.\n");
      out.write("    </p>\n");
      out.write("\n");
      out.write("    <h2>Add a New Movie Record</h2>\n");
      out.write("\n");
      out.write("    <p>\n");
      out.write("        Complete each field below. The movie ID is not entered by the user because it is\n");
      out.write("        created automatically by the database when the form is submitted.\n");
      out.write("    </p>\n");
      out.write("\n");
      out.write("    ");
 if (message != null && !message.isEmpty()) { 
      out.write("\n");
      out.write("        <p><strong>");
      out.print( message );
      out.write("</strong></p>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <form method=\"post\" action=\"index.jsp\">\n");
      out.write("        <label for=\"title\">Movie Title:</label>\n");
      out.write("        <input type=\"text\" id=\"title\" name=\"title\" required>\n");
      out.write("        <br><br>\n");
      out.write("\n");
      out.write("        <label for=\"director\">Director:</label>\n");
      out.write("        <input type=\"text\" id=\"director\" name=\"director\" required>\n");
      out.write("        <br><br>\n");
      out.write("\n");
      out.write("        <label for=\"release_year\">Release Year:</label>\n");
      out.write("        <input type=\"number\" id=\"release_year\" name=\"release_year\" required>\n");
      out.write("        <br><br>\n");
      out.write("\n");
      out.write("        <label for=\"genre\">Genre:</label>\n");
      out.write("        <input type=\"text\" id=\"genre\" name=\"genre\" required>\n");
      out.write("        <br><br>\n");
      out.write("\n");
      out.write("        <label for=\"rating\">Rating:</label>\n");
      out.write("        <input type=\"text\" id=\"rating\" name=\"rating\" required>\n");
      out.write("        <br><br>\n");
      out.write("\n");
      out.write("        <input type=\"submit\" value=\"Add Movie Record\">\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <h2>Current Movie Records</h2>\n");
      out.write("\n");
      out.write("    <p>\n");
      out.write("        The table below displays all records currently held in the movie database table.\n");
      out.write("        Each field is shown in its own column.\n");
      out.write("    </p>\n");
      out.write("\n");
      out.write("    <table border=\"1\">\n");
      out.write("        <thead>\n");
      out.write("            <tr>\n");
      out.write("                <th>Movie ID</th>\n");
      out.write("                <th>Title</th>\n");
      out.write("                <th>Director</th>\n");
      out.write("                <th>Release Year</th>\n");
      out.write("                <th>Genre</th>\n");
      out.write("                <th>Rating</th>\n");
      out.write("            </tr>\n");
      out.write("        </thead>\n");
      out.write("\n");
      out.write("        <tbody>\n");
      out.write("            ");
 for (String[] movie : movieRecords) { 
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( movie[0] );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( movie[1] );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( movie[2] );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( movie[3] );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( movie[4] );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( movie[5] );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
