/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-06-10 20:32:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    /*
        Java data section:
        This two-dimensional array stores the table records.
        Each record has three fields:
        1. Category
        2. Record Name
        3. Description
    */

    String pageTitle = "Florida Travel Records";

    String dataDescription = "This page displays a small set of records about Florida, "
            + "including places, food, nature, and activities that make the state interesting to visit.";

    String[][] records = {
        {"Attractions", "Orlando Theme Parks", "Florida is known for major theme parks and entertainment areas."},
        {"Attractions", "Kennedy Space Center", "This location shows Florida's connection to space exploration."},
        {"Nature", "Everglades National Park", "The Everglades has wetlands, wildlife, and airboat tours."},
        {"Food", "Key Lime Pie", "This dessert is one of Florida's most recognized foods."},
        {"Beaches", "Clearwater Beach", "Clearwater Beach is known for soft sand, ocean views, and relaxing scenery."}
    };

    String currentCategory = "";

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>");
      out.print( pageTitle );
      out.write("</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/styles.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <main class=\"page-container\">\n");
      out.write("        <header class=\"page-header\">\n");
      out.write("            <h1>");
      out.print( pageTitle );
      out.write("</h1>\n");
      out.write("            <p>");
      out.print( dataDescription );
      out.write("</p>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <section class=\"info-card\">\n");
      out.write("            <h2>Field Descriptions</h2>\n");
      out.write("            <p><strong>Category:</strong> Groups the record by topic.</p>\n");
      out.write("            <p><strong>Record Name:</strong> Names the specific place, food, or item being described.</p>\n");
      out.write("            <p><strong>Description:</strong> Explains why the record is important or interesting.</p>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"info-card\">\n");
      out.write("            <h2>Record Description</h2>\n");
      out.write("            <p>\n");
      out.write("                The records below are grouped into topical categories. Each row contains three fields\n");
      out.write("                and gives a short description related to visiting Florida.\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Category</th>\n");
      out.write("                        <th>Record Name</th>\n");
      out.write("                        <th>Description</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("\n");
      out.write("                <tbody>\n");
      out.write("                    ");
 for (int i = 0; i < records.length; i++) { 
      out.write("\n");
      out.write("\n");
      out.write("                        ");
 if (!records[i][0].equals(currentCategory)) { 
      out.write("\n");
      out.write("                            ");

                                currentCategory = records[i][0];
                            
      out.write("\n");
      out.write("                            <tr class=\"category-row\">\n");
      out.write("                                <td colspan=\"3\">");
      out.print( currentCategory );
      out.write("</td>\n");
      out.write("                            </tr>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>");
      out.print( records[i][0] );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( records[i][1] );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( records[i][2] );
      out.write("</td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <footer>\n");
      out.write("            <p>Created using JSP Scriptlets, HTML, and external CSS.</p>\n");
      out.write("        </footer>\n");
      out.write("    </main>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
